from environs import Env



env = Env()
env.read_env()

CLIENT_ID = env('CLIENT_ID')
CLIENT_SECRET = env('CLIENT_SECRET')
TOKEN = env('TOKEN')

CELERY_BROKER = env('CELERY_BROKER')
CELERY_BACKEND = env('CELERY_BACKEND')

URL_SYNC_HANDLER = env('URL_SYNC_HANDLER')

POSTGRESE_USER = env('POSTGRESE_USER')
POSTGRESE_PASSWORD = env('POSTGRESE_PASSWORD')
POSTGRES_DB = env('POSTGRES_DB')
HOST = env('HOST')
PORT = env('PORT')
TEST_POSTGRES_DB = env('TEST_POSTGRES_DB')

DATABASE_URL = f"postgresql+asyncpg://{POSTGRESE_USER}:{POSTGRESE_PASSWORD}@{HOST}:{PORT}/{POSTGRES_DB}"
DATABASE_SYNC_URL = f"postgresql+psycopg2://{POSTGRESE_USER}:{POSTGRESE_PASSWORD}@{HOST}:{PORT}/{POSTGRES_DB}"