from environs import Env



env = Env()
env.read_env(path="/yandex_service/settings.env")
env.read_env(path="/yandex_service/.env")

CLIENT_ID = env('CLIENT_ID')
CLIENT_SECRET = env('CLIENT_SECRET')

REDIS_HOST = env('REDIS_HOST')
REDIS_PORT = env('REDIS_PORT')

CELERY_BROKER = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/1"

POSTGRESE_USER = env('POSTGRESE_USER')
POSTGRESE_PASSWORD = env('POSTGRESE_PASSWORD')
POSTGRES_DB = env('POSTGRES_DB')
HOST = env('HOST')
PORT = env('PORT')
TEST_POSTGRES_DB = env('TEST_POSTGRES_DB')

DATABASE_URL = f"postgresql+asyncpg://{POSTGRESE_USER}:{POSTGRESE_PASSWORD}@{HOST}:{PORT}/{POSTGRES_DB}"
DATABASE_SYNC_URL = f"postgresql+psycopg2://{POSTGRESE_USER}:{POSTGRESE_PASSWORD}@{HOST}:{PORT}/{POSTGRES_DB}"

MAIN_HOST = env('MAIN_HOST')
MAIN_PORT = env('MAIN_PORT')

YANDEX_HOST = env('YANDEX_HOST')
YANDEX_PORT = env('YANDEX_PORT')