"""empty message

Revision ID: 1186fc7ebbaa
Revises: 
Create Date: 2023-08-06 20:23:47.321223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1186fc7ebbaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'service', ['token'])
    op.create_unique_constraint(None, 'service', ['user_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='unique')
    op.drop_constraint(None, 'service', type_='unique')
    # ### end Alembic commands ###
