"""empty message

Revision ID: 3a69a4307637
Revises: d43e72f34af5
Create Date: 2023-08-07 14:06:50.819699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a69a4307637'
down_revision = 'd43e72f34af5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('gps_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'gps_longitude')
    op.drop_column('media', 'gps_latitude')
    # ### end Alembic commands ###
