"""empty message

Revision ID: d43e72f34af5
Revises: 1186fc7ebbaa
Create Date: 2023-08-06 20:38:56.389476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43e72f34af5'
down_revision = '1186fc7ebbaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service_token_key', 'service', type_='unique')
    op.drop_constraint('service_user_email_key', 'service', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('service_user_email_key', 'service', ['user_email'])
    op.create_unique_constraint('service_token_key', 'service', ['token'])
    # ### end Alembic commands ###
