"""f

Revision ID: e7ac3088e783
Revises: 
Create Date: 2023-09-30 12:08:02.128328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ac3088e783'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('media', sa.Column('gps_latitude', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('gps_longitude', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'media', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'media', type_='unique')
    op.drop_column('media', 'gps_longitude')
    op.drop_column('media', 'gps_latitude')
    op.drop_table('used_tokens')
    # ### end Alembic commands ###
